// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SUs.KeepLatest.Cli.DataAccess;

namespace SUs.KeepLatest.Cli.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("SUs.KeepLatest.Cli.DataAccess.Models.KeepLatestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ItemLatestReleasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemLatestVer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemVer")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KeepLatestItems");
                });
#pragma warning restore 612, 618
        }
    }
}
